### ISSUE TITLE
Add globally installed Windows JRE to runtime path to include jawt

### ISSUE THREAD

**Issue by dextonanderson** [Ruinscraft/cinemadisplays-mod#1]
jawt Is required for JCEF to initialize. Using a launcher like MultiMC on Windows will use the globally installed JRE instead of the Mojang supplied JRE. When using the globally installed JRE, JCEF cannot find jawt.

**Comment by dextonanderson** [comment]
It's possible 3rd party launchers just won't be supported (officially)

**Comment by dextonanderson** [comment]
No longer should be an issue

**Comment by ItsK1tty** [comment]
offtopic, but is this mod a clone of montoyo/webdisplays?

**Comment by dextonanderson** [comment]
> offtopic, but is this mod a clone of montoyo/webdisplays?

It's not a clone, I wasnt aware webdisplays was a thing when I started this. I did eventually look at MCEF for examples on how to incorporate JCEF into MC

**Comment by ItsK1tty** [comment]
what is this then? a media player for minecraft?

**Comment by dextonanderson** [comment]
> what is this then? a media player for minecraft?

Essentially, yes. It embeds CEF into MC and is designed for watching videos with others on a multiplayer server. It was developed for https://stevecinema.com
